### ISSUE TITLE
Malisiscore 6.5.1 Compatibility 

### ISSUE THREAD

**Issue by LakMoore** [LakMoore/Smooth-Entity-Light#1]
Check compatibility with Malisiscore 6.5.1

**Comment by Titoo8899** [comment]
Yes compatibility is a problem in the begin of a mod. But I have a very bad Bug found with the Mod and water.

**Comment by LakMoore** [comment]
Compatibility is not a problem with this mod.  I have not yet found a single mod that is not compatible with Smooth Entity Light.  Your issue is discussed in #2 and I am yet to be convinced it is an issue with Smooth Entity Light.

**Comment by LakMoore** [comment]
Smooth Entity Light is confirmed as compatible with Malisiscore and all the Malisis mods.
