### ISSUE TITLE
Weird render problem with preview Optifine

### ISSUE THREAD

**Issue by Litttlefish** [LakMoore/Smooth-Entity-Light#15]
If you used these two together and enabled SEL instead of Optifine, the torch will act weirdly

![2020-08-06_20 04 54](https://user-images.githubusercontent.com/38809254/89530035-626bb380-d820-11ea-89ee-57d7d4ff2346.png)

**Comment by Litttlefish** [comment]
With VBOs enabling, if disabled the game will crash instantly

**Comment by LakMoore** [comment]
Yes, that makes sense.  Optifine is not compatible with this mod.  Both mods contain some similar changes but they take different approaches and the code will never be able to be compatible.
