### ISSUE TITLE
1.12.2 World was with Fog when I go in water and come out is the Fog in the world

### ISSUE THREAD

**Issue by Titoo8899** [LakMoore/Smooth-Entity-Light#2]
Hi,
I have with the 1.12.2 a Problem when I will play it. I have many thinks test. The Functions of the Commands /sel hand 0-15 work good. But it give a bug then I go in the Water. I have for the Fog the Mo "NoFog" from Tommeh2. And this mod is for clear the Fog. But then I go with my all download maps on a world was all normal. Then I go in Water the Fog is in the World. The way from the player in water and the way from Player in water out is a bug and the Fog is back and the NoFog Mod work but the Bug from your mod is over the other mod.  Hope you can fix this.

Name of all Mods with I work:
All MTS Mods
All FTB Mods
All Immersive Mods
All Oxygen Core ... Mods
many other mods with Dekoration and Items

Mods with Water and other World editing thinks:
- Smooth Entity Lights
- Smooth Zoom
- Worldedit
- Better Diving
- NoFog
- Jade
- lbm  (light blood mechanic)
- Core Mods

![2019-09-22_16 14 16](https://user-images.githubusercontent.com/42325138/65390150-e0d07b80-dd5c-11e9-9081-d60d55c15c27.png)
![2019-09-22_16 52 32](https://user-images.githubusercontent.com/42325138/65390151-e0d07b80-dd5c-11e9-913d-4f6d40cc18e2.png)

Link to NoFog: https://www.curseforge.com/minecraft/mc-mods/nofog

**Comment by Titoo8899** [comment]
Picture 1 show the Fog behind I was in the water and Picture 2 show before I was in the water to begin of the world enter. The City can you see in Picture 2 but then I was in the Water and go out of water to see the world the Fog is on.

**Comment by LakMoore** [comment]
How do you force fog ON in Minecraft?  I am unsure how to turn fog on, so I am struggling to test this problem.
I notice that you have a mod called "better diving", that may have something to do with changes when you enter and exit water!?

**Comment by Titoo8899** [comment]
Hi,
have testet with all mods and have your mod deleted with config and the same think with the Fog is on. Your mod have not the Problem. Thanks for the help.
