### ISSUE TITLE
Crashed after cutting a tree. Now crashing repeatedly?

### ISSUE THREAD

**Issue by Noxalas** [LakMoore/Smooth-Entity-Light#5]
This mod fit my needs perfectly and I really want to use it in my modpack,
but after playing with it for a while this crash happened.

https://paste.dimdev.org/omezegozer.mccrash

Can provide logs if necessary!

**Comment by LakMoore** [comment]
Thanks for the report.
Try v3.0.5, this should address your issue.  Please let me know how you get on.
